---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: development
spec:
  selector:
    app: pod-info
  ports:
    - protocol: TCP
      port: 1001
      targetPort: 3000
      
  type: LoadBalancer
