apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-info-app-deployment
  labels:
    app: pod-info-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-info-app
  template:
    metadata:
      labels:
        app: pod-info-app
    spec:
      containers:
      - name: pod-info-app
        image: kimschles/pod-info-app:latest
        ports:
        - containerPort: 8088 # Port changed to 8088
---
apiVersion: v1
kind: Service
metadata:
  name: pod-info-app-service
spec:
  selector:
    app: pod-info-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80 # The port the LoadBalancer will expose
      targetPort: 8088 # Port changed to 8088